[ClassVersion("1.0.0"), FriendlyName("PSDSCLog")]
class PSDSCLog : OMI_BaseResource
{
  [Key, Description("The id of the resource. Format: [Log]<resource name>")] String Resource;
  [Required, Description("The guid representing the running job. Format: {<guid>}")] String JobId;
  [Required, Description("The message to add to the Microsoft-Windows-Desired State Configuration/Analytic event log")] String Message;
};